name: Linter and type checks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "main"
      - "develop"

jobs:
  check:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.10"
      - run: pip install --upgrade pip
      - run: pip install "black<23" pylint mypy isort
      - run: pip install -r requirements.txt
      - run: mypy --install-types

      - name: Test black
        run: black -l79 --diff --check $(git ls-files 'src/*.py')

      - name: Test pylint
        run: pylint $(git ls-files 'src/*.py')

      - name: Test mypy
        run: mypy --ignore-missing-imports --strict $(git ls-files 'src/*.py')

      - name: Test isort
        run: isort -l79 -c --profile black $(git ls-files 'src/*.py')
